### ISSUE TITLE
possible break in upcoming REDCapR v1.2.0

### ISSUE THREAD

**Issue by wibeasley** [RaymondBalise/tidyREDCap#52]
@RaymondBalise & others, a [recent change in REDCap v13.4.10](https://redcap.vanderbilt.edu/community/post.php?id=203708) required a change in REDCapR (see https://github.com/OuhscBbmc/REDCapR/issues/479).  

I ran `revdepcheck::revdep_details()` and saw this error for your package.  I'd like to release to CRAN this weekend.

Is this failed check related to (a) REDCap's changes, (b) REDCapR's changes, or (c) something else?

https://github.com/OuhscBbmc/REDCapR/commit/c601dcd99e69dcb3a84e57f7b1403e3e6bdee72d

<details>
* Version: 1.1.0
* GitHub: https://github.com/RaymondBalise/tidyREDCap
* Source code: https://github.com/cran/tidyREDCap
* Date/Publication: 2023-02-18 18:10:02 UTC
* Number of recursive dependencies: 82
Run `revdepcheck::revdep_details(, "tidyREDCap")` for more info
</details>

## Newly broken

*   checking tests ...
    ```
      Running 'testthat.R'
     ERROR
    Running the tests in 'tests/testthat.R' failed.
    Last 13 lines of output:
        8.       │ └─rlang::try_fetch(...)
        9.       │   └─base::withCallingHandlers(...)
       10.       └─tidyselect:::vars_select_eval(...)
       11.         └─tidyselect:::ensure_named(...)
       12.           └─vctrs::vec_as_names(names(pos), repair = "check_unique", call = call)
       13.             └─vctrs (local) `<fn>`()
       14.               └─vctrs:::validate_unique(names = names, arg = arg, call = call)
       15.                 └─vctrs:::stop_names_must_be_unique(names, arg, call = call)
       16.                   └─vctrs:::stop_names(...)
       17.                     └─vctrs:::stop_vctrs(...)
       18.                       └─rlang::abort(message, class = c(class, "vctrs_error"), ..., call = call)
      
      [ FAIL 1 | WARN 0 | SKIP 0 | PASS 4 ]
      Error: Test failures
      Execution halted
    ```

**Comment by RaymondBalise** [comment]
Hi Will,
I don't know what that error is. So I am guessing here.  I there is a problem with tidyREDCap that is caused by the variable labels.  We have seen it throw an error that leads us to: https://vctrs.r-lib.org/reference/faq-error-incompatible-attributes.html .  We added `drop_labels` to deal with it.

**Comment by wibeasley** [comment]
I should have time this afternoon if you want to meet.

Don't worry about the details https://revdepcheck.r-lib.org/.  In this case, it basically (a) identifies the four packages that depend on REDCapR and (b) runs R CMD check on each to see if something breaks.  If the check fails, it tries to guess if it's because of REDCapR or if it's unrelated.

**Comment by RaymondBalise** [comment]
I have been in meetings for hours…  Send me a direct email ***@***.******@***.***>) if you have some time during the rest of the week.

Ray

Raymond R. Balise, PhD
Associate  Professor
Department of Public Health Sciences, Biostatistics

University of Miami, Miller School of Medicine
1120 N.W. 14th Street
Don Soffer Clinical Research Center - Room 1061
Miami, Florida 33136

(305) 243-9694

To request help from the Center for HIV and Research in Mental Health (CHARM) please go here<https://redcap.miami.edu/surveys/?s=EEWDYECME7>.  To provide post-consult feedback go here<https://redcap.miami.edu/surveys/?s=EYMEPRMCJP&consultant=1>. Please remember to acknowledge CHARM in your papers if resources were used (P30MH116867).

Confidentiality Notice: This e-mail transmission, and any documents, files or previous e-mail messages attached to it, may contain confidential information. If you are not the intended recipient, or a person responsible for delivering it to the intended recipient, you are hereby notified that any disclosure, copying, distribution or use of any of the information contained in or attached to this message is STRICTLY PROHIBITED. If you have received this transmission in error, please immediately notify us by reply e-mail or by telephone at (305) 243-9694  and destroy the original transmission and its attachments without reading them or saving them to disk.



From: Will Beasley ***@***.***>
Date: Monday, April 24, 2023 at 11:59 AM
To: RaymondBalise/tidyREDCap ***@***.***>
Cc: Balise, Raymond R ***@***.***>, Mention ***@***.***>
Subject: [EXTERNAL] Re: [RaymondBalise/tidyREDCap] possible break in upcoming REDCapR v1.2.0 (Issue #52)
CAUTION: This email originated from outside the organization. DO NOT CLICK ON LINKS or OPEN ATTACHMENTS unless you know and trust the sender.

I should have time this afternoon if you want to meet.

Don't worry about the details https://revdepcheck.r-lib.org/. In this case, it basically (a) identifies the four packages that depend on REDCapR and (b) runs R CMD check on each to see if something breaks. If the check fails, it tries to guess if it's because of REDCapR or if it's unrelated.
